/**
 * Decisions the colony agent makes from numbers, kept apart from the code that talks to the game.
 *
 * Everything here is a pure function of what the bridge reported, so each rule can be tested
 * without RimWorld running, and each one exists because a colony died without it:
 *
 *   - combat odds were guessed ("an animal with no weapon is worth 3"), so a naked founder took
 *     on, or ran from, animals the game rates far higher, and was downed every time;
 *   - "evade" meant running for a map corner, from animals that are faster than a person and
 *     birds that fly, and the corner was often unreachable anyway;
 *   - a bow was ordered to fire at targets thirty cells out and the order was refused;
 *   - the storyteller's scripted first week was treated as random, although the game fires the
 *     same incidents on the same ticks in every Cassandra and Phoebe run.
 *
 * Game numbers come from reference/game-data.json, regenerated by scripts/extract-game-data.py
 * from the installed game's own Defs.
 */
import { readFileSync } from "node:fs";

export const dist = (a, b) => Math.hypot((a?.x ?? 0) - (b?.x ?? 0), (a?.z ?? 0) - (b?.z ?? 0));

function loadGameData() {
  try {
    return JSON.parse(readFileSync(new URL("../reference/game-data.json", import.meta.url), "utf8"));
  } catch {
    return { animals: {}, people: {}, weapons: {}, humanMoveSpeed: 4.6 };
  }
}

export const GAME_DATA = loadGameData();

// ============================================================================
// The scripted first week
// ============================================================================

/**
 * RimWorld's StorytellerComp_ClassicIntro, read from Assembly-CSharp in 1.6.4871. Cassandra and
 * Phoebe both carry it; Randy does not. It fires on fixed ticks regardless of anything the colony
 * does:
 *
 *   150,000  day 3, 12h   friendly visitors, 40 to 100 points
 *   204,000  day 4, ~10h  one ThreatSmall incident: in practice a single wild animal of combat
 *                         power 40 or less (squirrel, rat, raccoon, vulture...) driven manhunter,
 *                         or with Anomaly a small shambler swarm
 *   264,000  day 5, ~10h  one Misc incident
 *   324,000  day 6, ~10h  a 40-point raid. One raider is forced to be downed instead of killed
 *                         and never flees on their own: a prisoner, if the colony can win.
 *
 * Five colonies journaled on 2026-09-22 and 23 lived to tick 204,000. All five met a hostile
 * within 300 ticks of it, three were downed by it, and one of the two survivors was kidnapped by
 * the 324,000 raid while starving through a mental break. None of that was bad luck; it was the
 * same two appointments, missed.
 */
export const INTRO_EVENTS = [
  { tick: 150000, kind: "visitors", label: "visitors arrive (a chance to trade)", threat: false },
  { tick: 204000, kind: "small-threat", label: "the first threat: one wild animal goes mad", threat: true },
  { tick: 264000, kind: "misc", label: "a random event", threat: false },
  { tick: 324000, kind: "intro-raid", label: "the first raid: one raider, who is taken alive if beaten", threat: true },
];

const INTRO_STORYTELLERS = /cassandra|phoebe/i;

/** Does this storyteller run the scripted intro? Unknown counts as yes: the default run is Cassandra. */
export function hasScriptedIntro(storyteller) {
  if (!storyteller) return true;
  return INTRO_STORYTELLERS.test(String(storyteller));
}

/** The next scripted incident after `tick`, or null once the first week is over. */
export function nextIntroEvent(tick, storyteller = null) {
  if (!hasScriptedIntro(storyteller)) return null;
  return INTRO_EVENTS.find((e) => e.tick > (tick ?? 0)) ?? null;
}

/**
 * A scripted threat that is due now: from `before` ticks ahead of it to `after` ticks past it.
 * 2,500 ticks is one in-game hour.
 */
export function scriptedThreatWindow(tick, storyteller = null, { before = 2500, after = 7500 } = {}) {
  if (!hasScriptedIntro(storyteller)) return null;
  const t = tick ?? 0;
  return INTRO_EVENTS.find((e) => e.threat && t >= e.tick - before && t <= e.tick + after) ?? null;
}

/** "day 4, 9h" for a tick, matching how the game counts days (day 1 starts at tick 0). */
export function tickToDayHour(tick) {
  const day = Math.floor(tick / 60000) + 1;
  const hour = Math.floor((tick % 60000) / 2500);
  return { day, hour, text: `day ${day}, ${hour}h` };
}

// ============================================================================
// Weapons, animals and people
// ============================================================================

/** "Short bow (normal)" -> "short bow"; quality and trailing detail are not part of the kind. */
export function cleanLabel(label) {
  return String(label ?? "").toLowerCase().replace(/\(.*?\)/g, "").replace(/\s+/g, " ").trim();
}

const RANGED_FALLBACK = /\b(bow|gun|rifle|pistol|revolver|shotgun|launcher|smg|carbine|lmg|minigun|pila|javelin|blowgun|spear thrower|charge)\b/;

/**
 * What a held weapon is, from the game's own table. Made-from-stuff weapons carry the stuff in
 * the label ("wooden club"), so the longest table entry contained in the label wins.
 */
export function weaponInfo(label) {
  const clean = cleanLabel(label);
  if (!clean) return null;
  const table = GAME_DATA.weapons ?? {};
  if (table[clean]) return { label: clean, ...table[clean] };
  let best = null;
  for (const key of Object.keys(table)) {
    if (key.length < 3 || !new RegExp(`(^|\\s)${key.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}($|\\s)`).test(clean)) continue;
    if (!best || key.length > best.length) best = key;
  }
  if (best) return { label: best, ...table[best] };
  const ranged = RANGED_FALLBACK.test(clean);
  return { label: clean, ranged, range: ranged ? 22 : null, guessed: true };
}

export const isRangedWeapon = (label) => Boolean(weaponInfo(label)?.ranged);

export function animalInfo(kind) {
  const k = cleanLabel(kind);
  return k ? (GAME_DATA.animals ?? {})[k] ?? null : null;
}

export function personInfo(kind) {
  const k = cleanLabel(kind);
  return k ? (GAME_DATA.people ?? {})[k] ?? null : null;
}

export function isHumanlikeThreat(t) {
  if (!t) return false;
  if (t.gender) return true;
  if (animalInfo(t.kind)) return false;
  if (personInfo(t.kind)) return true;
  return /raider|pirate|tribal|mercenary|scavenger|outlander|soldier|thief|warrior|grenadier|sniper|drifter|archer|berserker/i
    .test(`${t.kind ?? ""} ${t.faction ?? ""}`);
}

const healthFactor = (who) => Math.min(1, Math.max(0.2, who?.health?.pct ?? 1));

/**
 * How dangerous one hostile is, in the game's own combat power units. A colonist pawn kind is
 * 30, a drifter 35, a timber wolf 75, a grizzly 200.
 */
export function threatPower(t) {
  const known = animalInfo(t.kind)?.combatPower ?? personInfo(t.kind)?.combatPower;
  const base = known ?? (isHumanlikeThreat(t) ? 50 : 60);
  return base * healthFactor(t);
}

const skillLevel = (skills, key) => {
  const v = skills?.[key];
  return typeof v === "number" ? v : parseInt(String(v ?? "0"), 10) || 0;
};

/**
 * One colonist on the same scale. Calibrated against the game's own "colonist" kind (30): an
 * unarmed Melee-6 colonist lands there, a club adds about what a drifter's knife does, and a
 * bow adds more, because range decides most early fights. Hunger and wounds cut it.
 */
export function colonistPower(c, skills = {}) {
  if (!c || c.downed || c.dead || c.mentalState) return 0;
  const w = c.weapon ? weaponInfo(c.weapon) : null;
  let p = 22;
  if (w?.ranged) p += 18 + 1.5 * skillLevel(skills, "Shooting");
  else p += 1.3 * skillLevel(skills, "Melee") + (c.weapon ? 14 : 0);
  if ((c.needs?.food ?? 1) < 0.1) p *= 0.8;
  return p * healthFactor(c);
}

/**
 * Fight, or get behind a door. Never "run for the map edge".
 *
 * What each option costs, from the runs:
 *  - Running across open ground: every animal a founder has met is at least as fast as a person
 *    (4.6 cells/s), the Odyssey birds fly, and a hit with stopping power slows the runner to a
 *    sixth of their speed. The evading founders were caught and downed from behind, once while
 *    walking toward a corner the game said was unreachable.
 *  - A closed door: animals cannot open one at all, and raiders have to break it down. It is the
 *    only retreat that works, and only when the colonist reaches it first.
 *  - Standing to fight a small animal: the scripted day-4 threat is never above combat power 40.
 *    Even a naked colonist usually wins that, and winning ends it; hiding from a manhunter keeps
 *    the colonist from food until it wanders off.
 *
 * `shelter` is { x, z, usable } for the house's centre; usable means walls and a door stand.
 */
export function decideCombat({ colonists = [], threats = [], skills = new Map(), shelter = null } = {}) {
  const able = colonists.filter((c) => !c.downed && !c.dead && !c.mentalState && (c.health?.pct ?? 1) > 0.25);
  if (able.length === 0) return { posture: "helpless", reason: "nobody can act", ours: 0, theirs: 0 };

  const skillsOf = (c) => (skills instanceof Map ? skills.get(c.id) : skills?.[c.id]) ?? c.skills ?? {};
  const ours = able.reduce((a, c) => a + colonistPower(c, skillsOf(c)), 0);
  const theirs = threats.reduce((a, t) => a + threatPower(t), 0);
  const odds = `${Math.round(ours)} to ${Math.round(theirs)}`;
  const animalsOnly = threats.length > 0 && threats.every((t) => !isHumanlikeThreat(t));
  const contact = threats.some((t) => able.some((c) => dist(c, t) <= 2.5));
  const result = (posture, reason) => ({ posture, reason, ours, theirs });

  if (contact) return result("fight", `already in contact (${odds}); turning away hands them free hits`);
  if (animalsOnly && threats.every((t) => (animalInfo(t.kind)?.combatPower ?? Infinity) <= 45) &&
      able.some((c) => (c.health?.pct ?? 1) > 0.5)) {
    return result("fight", `small animal (${odds}); it is faster than us, so fighting ends it and running only means bites from behind`);
  }
  if (ours >= theirs * 0.8) return result("fight", `we outweigh them ${odds}`);

  const nearestThreatTo = (c) => Math.min(...threats.map((t) => dist(c, t)));
  const reachable = shelter?.usable && able.every((c) => {
    const toDoor = dist(c, shelter);
    return toDoor <= 20 && toDoor < nearestThreatTo(c);
  });
  if (reachable) {
    return result("shelter", `outmatched ${odds}; inside behind a door, which ${animalsOnly ? "animals cannot open" : "raiders have to break"}`);
  }
  return result("fight", `outmatched ${odds}, but there is nowhere safe to go: ${animalsOnly ? "animals outrun us" : "a runner gets shot or cut down from behind"}`);
}

/**
 * Where a ranged colonist should stand to take the shot, or null if it can shoot from here.
 * RimWorld refuses a drafted ranged attack on a target out of range ("Out of range") rather than
 * walking into range, so the agent has to close the distance itself. Stops at three quarters of
 * the weapon's reach, on the line toward the target.
 */
export function approachPoint(from, target, range, mapSize = 250) {
  const d = dist(from, target);
  if (!range || d <= range * 0.9) return null;
  const want = Math.max(4, range * 0.75);
  const ux = (from.x - target.x) / d, uz = (from.z - target.z) / d;
  const clamp = (v) => Math.round(Math.min(mapSize - 3, Math.max(2, v)));
  return { x: clamp(target.x + ux * want), z: clamp(target.z + uz * want) };
}

// ============================================================================
// Phases
// ============================================================================

/**
 * Should the colony be in the food phase? With hysteresis, so it stops flipping.
 *
 * Every journal showed the phase changing between "food" and "house" about once a minute: a pawn
 * at 27% food eats a stack of berries, reads 50%, the phase flips to building, and an hour later
 * it flips back. Each flip re-narrated a "new objective" to the stream. Entering the food phase
 * keeps the old thresholds; leaving it now needs a real margin.
 */
export function wantsFoodPhase({ hungriest, supply, earlyBaseNeeded, inFoodPhase }) {
  const enter = hungriest < 0.28 || (hungriest < 0.45 && supply < 0.3) ||
    (!earlyBaseNeeded && (hungriest < 0.45 || supply < 1.5));
  if (!inFoodPhase) return enter;
  return hungriest < 0.38 || (hungriest < 0.55 && supply < 0.5) ||
    (!earlyBaseNeeded && (hungriest < 0.55 || supply < 2.0));
}

// ============================================================================
// Ideology
// ============================================================================

/**
 * Which kind of weapon the colony's ideoligion wants, read from the pawn's own thoughts.
 *
 * With Ideology active a random start can despise ranged or melee weapons. One founder carried a
 * despised short bow for nine days: "Used despised weapon" and "Wielding a short bow" were minus
 * ten mood between them, every day, on a pawn that broke at thirty. The thought names the problem;
 * this reads it. Returns "melee", "ranged" or null.
 */
export function weaponPreferenceFromThoughts(thoughts = [], currentWeapon = null) {
  const despised = thoughts.map(String).some((t) => /despised weapon/i.test(t));
  if (!despised || !currentWeapon) return null;
  return isRangedWeapon(currentWeapon) ? "melee" : "ranged";
}
